spring.application.name=Order
server.port=8082
inventory.service.baseurl=http://localhost:8081
inventory.service.url=${inventory.service.baseurl}/api/v1/inventory

#Postgres database
spring.datasource.url=jdbc:postgresql://localhost:5432/playground
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

#H2 database - INIT=CREATE SCHEMA IF NOT EXISTS MAPPING
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=sa
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#logging
logging.level.root=info
logging.level.com.pg.ms.order=debug
spring.output.ansi.enabled=always

#show Binding parameters values
logging.level.org.hibernate.type.descriptor.sql=trace

#Feign client configuration
spring.cloud.openfeign.client.config.default.connectTimeout=5000
spring.cloud.openfeign.client.config.default.readTimeout=65000
spring.cloud.openfeign.client.config.default.loggerLevel=full
